[2025-04-10T22:08:15.102+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-10T22:08:15.118+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_operator.hello_with_python manual__2025-04-10T22:08:14.466591+00:00 [queued]>
[2025-04-10T22:08:15.126+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_operator.hello_with_python manual__2025-04-10T22:08:14.466591+00:00 [queued]>
[2025-04-10T22:08:15.127+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-10T22:08:15.141+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): hello_with_python> on 2025-04-10 22:08:14.466591+00:00
[2025-04-10T22:08:15.147+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=910) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-10T22:08:15.149+0000] {standard_task_runner.py:72} INFO - Started process 913 to run task
[2025-04-10T22:08:15.149+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'python_operator', 'hello_with_python', 'manual__2025-04-10T22:08:14.466591+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/2-pythonoperator.py', '--cfg-path', '/tmp/tmp61t33hls']
[2025-04-10T22:08:15.150+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask hello_with_python
[2025-04-10T22:08:15.189+0000] {task_command.py:467} INFO - Running <TaskInstance: python_operator.hello_with_python manual__2025-04-10T22:08:14.466591+00:00 [running]> on host 241bfdac645b
[2025-04-10T22:08:15.251+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='python_operator' AIRFLOW_CTX_TASK_ID='hello_with_python' AIRFLOW_CTX_EXECUTION_DATE='2025-04-10T22:08:14.466591+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-10T22:08:14.466591+00:00'
[2025-04-10T22:08:15.253+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-10T22:08:15.273+0000] {logging_mixin.py:190} INFO - Hello people from python funtion
[2025-04-10T22:08:15.274+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-10T22:08:15.282+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-10T22:08:15.283+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=python_operator, task_id=hello_with_python, run_id=manual__2025-04-10T22:08:14.466591+00:00, execution_date=20250410T220814, start_date=20250410T220815, end_date=20250410T220815
[2025-04-10T22:08:15.324+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-10T22:08:15.339+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-10T22:08:15.344+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
